# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 2
      - name: Set up correct version of Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6
        # Use bundler version mentioned in Gemfile.lock
        # https://discuss.circleci.com/t/using-bundler-2-0-during-ci-fails/27411/3
      - name: Configure Bundler
        run: |
          gem uninstall bundler
          BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")
          gem install bundler -v $BUNDLER_VERSION
          bundle install --jobs 4 --retry 3
      - name: Which ruby?
        run: ruby -v
      - name: Which gem?
        run: gem -v
      - name: Which bundler?
        run: bundle -v
      - name: Configure DB for RSpec
        run: |
          cp config/database.yml.example config/database.yml
          bundle exec rake db:setup
      - name: Compile assets
        run: |
          bundle exec rails webpacker:install
          bundle exec rails webpacker:compile
      - name: Run RSpec
        run: COVERAGE=true bundle exec rspec
      - run: echo "PACKAGE_JSON=$(jq -c . < /home/runner/work/slot-booking-app/slot-booking-app/coverage/.last_run.json)" >> $GITHUB_ENV

      - run: echo '${{ fromJson(env.PACKAGE_JSON).result.line }}'

      - name: getParams
        id: coverage
        run: |
          content=$(jq -c . < /home/runner/work/slot-booking-app/slot-booking-app/coverage/.last_run.json)
          echo "last_result_content=${content}" >> $GITHUB_OUTPUT
      - run: echo "COVERAGE=${{ fromJson(steps.coverage.outputs.last_result_content).result.line }}"  >> $GITHUB_ENV
      - name: getParams
        id: nums2
        run: |
          echo "num_val=$(echo ${env.COVERAGE})" >> $GITHUB_OUTPUT
      - name: getParams
        id: nums
        run: |
          echo "num_val=${{env.COVERAGE}}" >> $GITHUB_OUTPUT
          
      - run: |
          echo "TEST_THIS=$( echo 'scale=4;20+5/2' | bc )" >> $GITHUB_ENV
      - run: ruby -e 'p 22.33.round'
      - run: |
          echo "TEST_THIS3=$( ruby -e 'p 22.33.round' )" >> $GITHUB_ENV
            
      - run: |
          gb=23.56766
          echo "TEST_THIS4=$( ruby -e 'p (`gb`/7).round' )" >> $GITHUB_ENV
      - run: |
          gb=23.56766
          echo "TEST_THIS2=$( echo 'scale=4;$gb+5/2' | bc )" >> $GITHUB_ENV
      
      - run: echo '${{ env.TEST_THIS }}'
      - run: echo '${{ env.TEST_THIS2 }}'
      - run: echo '${{ env.TEST_THIS3 }}'
      - run: echo '${{ env.TEST_THIS4 }}'

      - name: Test num
        env:
          NUM: ${{ steps.nums.outputs.num_val }}
        run: |
          echo "($NUM+0.5)/1"
          
      - run: |
          gb=23.56766
          echo "($gb+0.5)/1"
      - run: |
          gb=23.56766
          echo "test1=$( echo "($gb+0.5)/1" )" >> $GITHUB_ENV
      - run: |
          gb=23.56766
          echo "test2=$( echo "(gb+0.5)/1" )" >> $GITHUB_ENV
      
      - run: echo '${{ env.test1 }}'
      - run: echo '${{ env.test2 }}'


      - run: echo '${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}'
      - run: echo '${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET2 }}'

      - run: echo "num_val_2=${{env.COVERAGE}}" >> $GITHUB_OUTPUT
      - run: echo '${{ steps.outputs.num_val_2 }}'

      - name: Get Coverage for badge
        run: |
          REF=${{ github.ref }}
          echo "github.ref: $REF"
          IFS='/' read -ra PATHS <<< "$REF"
          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          echo $BRANCH_NAME
          echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6cfb4fc7d7e50f7158c03890c1a4a513
          filename: slot-booking-app__${{ env.BRANCH }}.json
          label: Test Coverage
          message: "${{ env.COVERAGE }}%"
          valColorRange: ${{ env.COVERAGE }}
          maxColorRange: 100
          minColorRange: 0
